### ISSUE TITLE
Screen brightness randomly reduces to zero

### ISSUE THREAD

**Issue by e-senturk** [black-dragon74/ROG-HID#1]
I find a way to install this driver without xcode.
1- Download app and copy it application folder.
2- Click activate and close app(Repeat it few times until it wants a permission)
3- Go settings/Security and allow rog hid.
4- Reopen app and click activate one more time.
5- Restart computer.

-In Catalina and Bigsur Backlight and Keyboard backlight controls working well but capslock light is not working. Device 0b05:1866
Bug: Sometimes screen brightness reduces itself to zero.

**Comment by black-dragon74** [comment]
Thanks for confirming that pre-signed app works for other users with SIP disabled.

About CAPS Lock key, does the text capitalization work? Have you tried pressing multiple times? Actually, for some reason all ROG HID keyboards with an CAPS lock led suffer from this problem. I managed to fix it on 0b05:1869.

Screen brightness reduces itself to zero when you press and hold the decrease brightness key or randomly (even when you don’t press anything).

For other Fn key features, please have a look at the README. They’ll be implemented in a future release. DriverKit has zero documentation as of now -_-

**Comment by e-senturk** [comment]
-Screen brightness reduces itself to zero when you press and hold the decrease brightness key or randomly
--In my case it happens randomly or I didnt see a pattern.
-Text capitalization works I have capslock led as well but led is not working even with that kext

**Comment by black-dragon74** [comment]
If it doesn’t occur when pressing a key. I don’t think it’s related to ROG-HID. As the driver only dispatches events to system on keypress. Still I have a hunch that it might be related to #2 

Did CAPS Lock LED ever work for you without the driver? We can always set caps lock led state by calling `_hid_interface->SetLED(0x2,0)` where 0 means off and 1 means on. But it doesn’t actually toggle the CAPS Lock state.

**Comment by black-dragon74** [comment]
@valinor61 Your weird behavior of brightness keys must be fixed now. Please try the latest release. To fix LED, I need to know if the LED ever actually worked on macOS without my driver?

P.S: I have updated the README to simplify the installation process. Thanks for confirming.

**Comment by e-senturk** [comment]
Yes it fixed now. It was M key I tested now working without issue. Capslock led is not working with v1.1 and it has never worked in osx.

**Comment by black-dragon74** [comment]
Ok great! Now for CAPS Lock LED, If it has never worked before, I would need to have access to hardware in order to debug it. So, unfortunately, that's not possible for me to fix as of now.

The fix that is there in this driver for CAPS Lock LED doesn't fix the LED itself but the erratic behavior of it. Meaning, LED works without this driver too, just not reliably.

Closing this issue.
