### ISSUE TITLE
ROG HID need Permisiion

### ISSUE THREAD

**Issue by dikatuex** [black-dragon74/ROG-HID#11]
Hello
I can't open this application (MacOS Big Sur 11.0.1 (20B29) )
there is an error like this :

[https://i.postimg.cc/267RYwX9/Screen-Shot-2020-12-27-at-23-08-08.png](url)

Process:               ROG-HID [9963]
Path:                  /Applications/ROG-HID.app/Contents/MacOS/ROG-HID
Identifier:            ROG-HID
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ROG-HID [9963]
User ID:               501

Date/Time:             2020-12-27 23:07:31.153 +0700
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        983FB42F-2D8E-67B9-E86D-EA3B8945CC74

Time Awake Since Boot: 5900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                      108b1d000-108b25000    [   32K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x00000001173a7000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee70e2bf0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00000001173a7000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Thread 0 instruction stream not available.

Thread 0 last branch register state not available.

Binary Images:
       0x108b1d000 -        0x108b24fff +??? (0) <F88A1CA7-2E06-37F0-8D87-702F2A97E927> (null)
       0x1173a6000 -        0x117441fff +??? (832.7.1) <2705F0D8-C104-3DE9-BEB5-B1EF6E28656D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 11674
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=952K resident=0K(0%) swapped_out_or_unallocated=952K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             240K        3 
__DATA_CONST                        48K        2 
__LINKEDIT                         320K        4 
__TEXT                             656K        2 
===========                     =======  ======= 
TOTAL                             65.2M       13 

Model: MacBookPro15,2, BootROM 1554.50.3.0.0, 4 processors, Quad-Core Intel Core i5, 2,4 GHz, 8 GB, SMC 
Graphics: Intel UHD Graphics 630 macOS Edition, Intel UHD Graphics 630 macOS Edition, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-3G2J1
AirPort: spairport_wireless_card_type_airport_extreme (0x8086, 0x34), itlwm: 1.2.0 fw: 34.3125811985.0
Bluetooth: Version 8.0.1f5, 3 services, 24 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Intel UHD Graphics 630 macOS Edition, Display Controller, Built-In
PCI Card: Coffee Lake USB 3.1 xHCI Host Controller, USB controller, Internal@0,20,0
PCI Card: Intel Wireless-AC 9560, Network controller, Internal@0,20,3
PCI Card: Coffee Lake I2C Controller #0, Serial bus controller, Internal@0,21,0
PCI Card: Coffee Lake I2C Controller #1, Serial bus controller, Internal@0,21,1
PCI Card: Coffee Lake HECI Controller, Communication controller, Internal@0,22,0
PCI Card: Coffee Lake Mobile SATA AHCI Controller, SATA controller, Internal@0,23,0
PCI Card: Realtek ALC294, Audio device, Internal@0,31,3
PCI Card: Coffee Lake SMBus Controller, SMBus, Internal@0,31,4
PCI Card: Realtek RTL8168H/8111H PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,29,6/0,0
Serial ATA Device: SDVPSA1910128, 128,04 GB
USB Device: USB 3.1 Bus
USB Device: Bluetooth HCI
USB Device: N-KEY Device
USB Device: USB Mouse
Thunderbolt Bus:

**Comment by black-dragon74** [comment]
Disable SIP
