### ISSUE TITLE
Not work for bigsur and monterey asus rog gl503vd

### ISSUE THREAD

**Issue by fauzisunarya** [black-dragon74/ROG-HID#22]
solution please
https://user-images.githubusercontent.com/43233727/180683150-6dbe02a5-8de0-4ba8-a5ea-8ee4ae01745c.mp4

**Comment by black-dragon74** [comment]
Working fine for me here (on latest macOS version). Please make sure you follow the README properly. 

Alternatively, try the latest release. 

Make sure running `systemextensionsctl developer` returns "Developer mode is on". 

If not, you can enable it by running `systemextensionsctl developer on` in the Terminal.

<img width="2048" alt="Screen Shot 2022-07-25 at 4 45 32 PM" src="https://user-images.githubusercontent.com/13179334/180766119-b90f7ec5-47d2-4fe5-978b-9120c8a3251a.png">

Regards

**Comment by fauzisunarya** [comment]
Hallo sir please help me
dext file is not in the System Extensions folder

![Screen Shot 2022-07-26 at 14 07 10](https://user-images.githubusercontent.com/43233727/180945364-48d06752-10cc-4caa-a996-8bf3bf31954c.png)

**Comment by fauzisunarya** [comment]
Solved sir thanks, i try disablle SIP and its works
