### ISSUE TITLE
Unable to open in macOS 12.6.6

### ISSUE THREAD

**Issue by weizhuangzheX** [black-dragon74/ROG-HID#25]
Hello, may I ask if this can be opened directly after downloading? I sent it on macOS12.6.6 and opened it. Below is the report, hoping to receive answers. Thank you very much!!!

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: E9CF3E8E-A4EE-4898-885D-7B950A2E77C2
CrashReporter Key:   28979349-54B3-8AAB-4E1A-1A14B1E03B1D
Hardware Model:      MacBookPro16,3
Process:             ROG-HID [2610]
Path:                /Users/USER/Downloads/ROG-HID.app/Contents/MacOS/ROG-HID
Identifier:          com.black-dragon74.ROG-HID
Version:             1.3 (1)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.black-dragon74.ROG-HID [2847]

Date/Time:           2023-06-07 15:51:09.7257 +0800
Launch Time:         2023-06-07 15:51:09.6850 +0800
OS Version:          macOS 12.6.6 (21G639)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Triggered by Thread:  0

Thread 0 Crashed:
0                                	       0x10d646ae0 _dyld_start + 0
1   ???                           	               0x1 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b5c2fbf0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010d646ae0  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0

Binary Images:
       0x10d642000 -        0x10d6adfff  (*) <2517e9fe-884a-3855-8532-92bffba3f81c> 
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"ROG-HID","timestamp":"2023-06-07 15:51:09.00 +0800","app_version":"1.3","slice_uuid":"c3c90567-4687-3b98-a80b-79863c1b24c3","build_version":"1","platform":0,"bundleID":"com.black-dragon74.ROG-HID","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.6 (21G639)","incident_id":"E9CF3E8E-A4EE-4898-885D-7B950A2E77C2","name":"ROG-HID"}
{
  "uptime" : 1100,
  "procLaunch" : "2023-06-07 15:51:09.6850 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,3",
  "procStartAbsTime" : 1107519077948,
  "coalitionID" : 2847,
  "osVersion" : {
    "train" : "macOS 12.6.6",
    "build" : "21G639",
    "releaseType" : "User"
  },
  "captureTime" : "2023-06-07 15:51:09.7257 +0800",
  "incident" : "E9CF3E8E-A4EE-4898-885D-7B950A2E77C2",
  "bug_type" : "309",
  "pid" : 2610,
  "procExitAbsTime" : 1107559527723,
  "cpuType" : "X86-64",
  "procName" : "ROG-HID",
  "procPath" : "\/Users\/USER\/Downloads\/ROG-HID.app\/Contents\/MacOS\/ROG-HID",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3","CFBundleVersion":"1","CFBundleIdentifier":"com.black-dragon74.ROG-HID"},
  "storeInfo" : {"deviceIdentifierForVendor":"04A438CD-E2E2-5023-84C9-C2B5461B0989","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.black-dragon74.ROG-HID",
  "crashReporterKey" : "28979349-54B3-8AAB-4E1A-1A14B1E03B1D",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"namespace":"CODESIGNING","flags":66,"code":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":27095,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4519652064,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701883104240},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":19168,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":1,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4519632896,
    "size" : 442368,
    "uuid" : "2517e9fe-884a-3855-8532-92bffba3f81c",
    "path" : "\u0004",
    "name" : "\u0004"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=732K resident=0K(0%) swapped_out_or_unallocated=732K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              32K        2 \n__DATA_CONST                        96K        2 \n__LINKEDIT                         288K        4 \n__TEXT                             464K        2 \n===========                     =======  ======= \nTOTAL                             64.9M       14 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000614
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000005
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro16,3, BootROM 1968.100.17.0.0, 8 processors, AMD Ryzen™ 9 5900HX, 3.3 GHz, 32 GB, SMC 
Graphics: AMD Radeon Graphics, AMD Radeon Graphics, PCIe, 8 GB
Display: TL156VDXP01, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: P0 CHANNEL A/DIMM 0, 16 GB, DDR4, 3200 MHz, Samsung, M471A2K43DB1-CWE
Memory Module: P0 CHANNEL B/DIMM 0, 16 GB, DDR4, 3200 MHz, Samsung, M471A2K43DB1-CWE
AirPort: spairport_wireless_card_type_wifi (0x8086, 0x24), itlwm: 2.2.0 fw: 68.01d30b0c.0
AirPort: 
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB31Bus
USB Device: Bluetooth USB Host Controller
USB Device: USB Disk
USB Device: Smart Wireless Device
USB Device: USB31Bus
USB Device: USB3 Video
USB Device: N-KEY Device
USB Device: USB Receiver
Thunderbolt Bus: 
![QQ20230607-155135](https://github.com/black-dragon74/ROG-HID/assets/42230059/9bc2c857-1186-446b-a4c8-62fa5bfe7b02)

**Comment by edwin170** [comment]
hi, did you fix it ?
