### ISSUE TITLE
Unable to load the dext

### ISSUE THREAD

**Issue by manashathparia** [black-dragon74/ROG-HID#3]
The app does nothing when clicked the active button. It doesn't ask for permission nor anything happens

**Comment by black-dragon74** [comment]
Please have a full read of README.
.
If you choose not to, make sure your SIP is disabled and `systemextensionsctl` developer mode is on.

**Comment by manashathparia** [comment]
SIP is already disabled and I also tried turning on systemextensionsctl developer mode but still same. Nothing happens

**Comment by black-dragon74** [comment]
Type `log stream --source | grep "com.black-dragon74.ROG-HID-Driver"` in terminal and then open the app and click on activate extension. Post the output here.

**Comment by manashathparia** [comment]
here is log: 
2020-07-29 09:11:43.704570-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: attempting to realize extension with identifier com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.721503-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: staging extension with identifier com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.736024-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: Making activation decision for extension with teamID teamID("LUPK75PW6Q"), identifier com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.736096-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: validating extension with identifier com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.748402-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: uninstalling invalid extension com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.751149-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: finished uninstalling extension com.black-dragon74.ROG-HID-Driver
2020-07-29 09:11:43.751208-0700 0x19f8     Default     0x327e               438    0    <sysextd> sysextd: waiting for external validation of extension with identifier com.black-dragon74.ROG-HID-Driver

**Comment by e-senturk** [comment]
1- Download app and copy it application folder.
2- Click activate and close app(Repeat it few times until it wants a permission)
3- Go settings/Security and allow rog hid.
4- Reopen app and click activate one more time.
5- Restart computer.
Try this

**Comment by manashathparia** [comment]
> Click activate and close app(Repeat it few times until it wants a permission)

I did this step around 20 times still no Permission popup

**Comment by black-dragon74** [comment]
@valinor61 above steps are un-necessary. If you don't get a popup, you can reset systemextensionsctl catalog by running `systemextensionsctl reset` and then can try again by opening the app.

@manashathparia Try resetting the catalog and also, If you are not getting a popup even after resetting, something is wrong with your setup (SIP or Developer mode)

The extension is working on both Catalina and BigSur.

**Comment by e-senturk** [comment]
I did all but it shown me on third time thats why I said try repeatedly

**Comment by manashathparia** [comment]
I reinstalled macOS Catalina 10.15.4 and tried with SIP disabled and developer mode enabled but it's still not working

**Comment by black-dragon74** [comment]
@manashathparia Post your IOREG, and output of `systemextensionsctl developer` and `nvram -p | grep 'csr-active-config'`

**Comment by manashathparia** [comment]
Here is the terminal output, nvram command didnt returned anything so i attached csrutil status.

manash@Manashs-MBP ~ % systemextensionsctl developer
Developer mode is on
manash@Manashs-MBP ~ % nvram -p | grep 'csr-active-config'
manash@Manashs-MBP ~ % csrutil status
System Integrity Protection status: disabled.
manash@Manashs-MBP ~ % 

[Manash’s MacBook Pro IOREG.zip](https://github.com/black-dragon74/ROG-HID/files/5006445/Manash.s.MacBook.Pro.zip)

**Comment by black-dragon74** [comment]
Your SIP is not disabled. Set `csr-active-config` nvram variable value to `e7 03 00 00` . You can verify if SIP is disabled or not by running `nvram -p | grep 'csr-active-config'` the output should be `csr-active-config	%e7%03%00%00`

**Comment by manashathparia** [comment]
I thought setting 0x67 in CsrActivateConfig in clover config.plist disables it completely and also the csrutil status is showing disabled

**Comment by manashathparia** [comment]
> `csr-active-config` nvram variable value to `e7 03 00 00`

I think this implies to opencore not clover. In clover CsrActivateConfig - 0x67 is used to disable SIP.

**Comment by manashathparia** [comment]
Can the driver be manually installed? or any other workaround?

**Comment by trankimlonghai** [comment]
@black-dragon74  Hi, can you take a look into this ? I tried reset systemextensionsctl reset as well as disable SIP but app still not show anything after I click Activate ROG HID, I'm running 10.15.7
https://i.imgur.com/j1tEEr5.png

**Comment by black-dragon74** [comment]
There is no image.

**Comment by trankimlonghai** [comment]
> There is no image.

sorry I've just editted the link: https://i.imgur.com/j1tEEr5.png

**Comment by trankimlonghai** [comment]
@black-dragon74  I also made sure developer mode is on, but click on activate ROG HID nothing happened, deactivated then activated it, says it was blocked, I allowed it security and privacy (although I disabled gatekeeper) => click activate again => still nothing happens
