### ISSUE TITLE
doesn't work on big sur 11.1

### ISSUE THREAD

**Issue by dxh000130** [black-dragon74/ROG-HID#8]
ROG-HID and macRogAuraCore doesn't work on big sur 11.1. The keyboard is not responding. 
id 1866 0b05

**Comment by black-dragon74** [comment]
Last I checked, it worked on Beta 1. I haven't upgraded to BS yet. Also, can't really tell much without logs.

**Comment by dxh000130** [comment]
thia ia report
[report.zip](https://github.com/black-dragon74/ROG-HID/files/5594950/report.zip)

**Comment by dxh000130** [comment]
this is log
[log.txt](https://github.com/black-dragon74/ROG-HID/files/5595031/log.txt)

**Comment by black-dragon74** [comment]
Hey @dxh000130, I've identified the issue. It's a `SIGSEV`. Something changed in the framework. I don't have much free time these days but I'll try to fix this ASAP.

Regards

**Comment by black-dragon74** [comment]
Also, meanwhile you can use [ROGSwitch](https://github.com/black-dragon74/ROGSwitch) to control your keyboard. You can use the version I am attaching here (it allows you to turn lights on and off from the menu bar)

Download from here: [ROGSwitch.zip](https://github.com/black-dragon74/ROG-HID/files/5702155/ROGSwitch.zip)

Regards

**Comment by dxh000130** [comment]
Haha, Don't try so hard.
Thanks
Regards

**Comment by black-dragon74** [comment]
Fixed at: 3a3cc381b9e338b95a813a6ac6a3928474de1db2
